FROM ubuntu:24.10

RUN apt update

# In ubuntu 24.10 install package with apt
RUN apt install -y curl vim nginx

#
# Nodejs
#
RUN curl -sL https://deb.nodesource.com/setup_20.x | bash -
RUN apt install -y nodejs
RUN npm i -g next

RUN mkdir -p /app

EXPOSE 3000 443