"use client";
import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const router = useRouter();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-b border-b-slate-900 py-5 flex justify-center items-center gap-5">
          <Link href="/" className="text-lg">
            Beranda
          </Link>
          <button
            className="text-lg bg-gray-950 text-white p-2 px-3 rounded-md"
            onClick={() => router.push("/")}
          >
            About
          </button>
          <Link href="/dashboard/settings" className="text-lg">
            Settings
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
