import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="border-b border-b-slate-900 py-5 flex justify-center items-center gap-5">
          <Link href="/" className="text-xl">
            Beranda
          </Link>
          <Link href="/about" className="text-xl">
            About
          </Link>
          <Link href="/dashboard/settings" className="text-xl">
            Settings
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
